spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smallbluevolume?serverTimezone=GMT%2B8&useSSL=true
    username: root   #数据库
    password: 12345678 #密码
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
